baseURL = 'https://codersonlych.github.io/'
languageCode = 'en-US'
title = 'Coders Only'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'What We Do'
pageRef = '/what-we-do'
weight = 20

[[menus.main]]
name = 'Past Events'
pageRef = '/posts'
weight = 30

[[menus.main]]
name = 'Association'
pageRef = '/verein'
weight = 40

[[menus.main]]
name = 'About'
pageRef = '/about-us'
weight = 50

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
