name: Build and Deploy Marp Slides

on:
  push:
    branches:
      - main  # Adjust to your default branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Marp CLI
        run: npm install -g @marp-team/marp-cli

      - name: Build Marp slides
        run: |
          for mdfile in $(find . -name '*.md'); do
            output_file="public/${mdfile%.md}.html"
            mkdir -p "$(dirname $output_file)"
            marp --html \
              --theme-set "marp/themes" \
              --output "$output_file" \
              "$mdfile"
          done

      - name: Copy marp themes
        run: |
          mkdir -p public/marp/themes
          rsync -av --exclude='*.nix' marp/themes/ public/marp/themes/

      - name: Copy assets
        run: |
          find . -type d -name "assets" -print0 | while IFS= read -r -d '' dir; do
            rsync -av --exclude='*.nix' "$dir/" "public/${dir#./}/"
          done

      - name: Generate index
        run: |
          cat<<\EOF >> public/index.html
          <!DOCTYPE html>
          <html><head><title>Coders Only Slides</title></head><body>
          <ul>
          EOF

          find public -type f -name "*.html" ! -name "index.html" | sort | while read file; do
            relative_path="${file#public/}"
            echo "<li><a href=\"$relative_path\">$relative_path</a></li>" >> public/index.html
          done

          cat<<\EOF >> public/index.html
          </ul>
          </body>
          </html>
          EOF

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
